name: canna_go_dev
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider:
  http:
  redux:
  flutter_redux:
  redux_thunk:
  datetime_picker_formfield:
  shared_preferences:
  json_serializable:
  build_runner:
  google_maps_flutter:
  smooth_star_rating:
  geocoder: ^0.2.1
  location:
  connectivity:
  firebase_messaging:
  geopoint:
  braintree_payment: ^1.2.2
  #flutter_country_picker:
  image_picker:
  image_cropper:
  adhara_socket_io:
  toast:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/g2.png
   - assets/img/med.jpg
   - assets/img/d.jpg
   - assets/img/camera.png
   - assets/img/shopbc.png
   - assets/img/ph.jpg
   - assets/img/internet.png
   - assets/img/profile.png
   - assets/img/taxi.png
   - assets/img/medicine.jpg
   - assets/img/shopBanner.jpg
   - assets/img/shopItem.jpg
   - assets/img/medicine_icon.PNG
   - assets/img/completed.jpg
   - assets/img/driver_found.jpg
   - assets/img/cancel.jpg
   - assets/img/status.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyriadPro
      fonts:
        - asset: fonts/MyriadPro-Bold.otf
          weight: 900
        - asset: fonts/MyriadPro-Regular.otf
          weight: 400
    - family: sourcesanspro
      fonts:
        - asset: fonts/sourcesanspro-bold.otf
          weight: 900
        - asset: fonts/sourcesanspro-semibold.otf
          weight: 700
        - asset: fonts/sourcesanspro-light.otf
          weight: 300
        - asset: fonts/sourcesanspro-regular.otf
          weight: 400
    - family: DINPro
      fonts:
        - asset: fonts/DINPro-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages